[package]
name = "convert"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.0", features = ["derive"] }
miller_rabin_primality_test = { git = "https://github.com/gilflorida2023/miller_rabin_primality_test.git", branch = "master" }
