[package]
name = "convert"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.0", features = ["derive"] }
#miller-rabin-primality-test = { git = "https://github.com/Sparrow-guy/miller-rabin-primality-test-rust.git", branch = "main" }